package telemetry

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"strings"
	"sync/atomic"

	"github.com/tdeslauriers/carapace/pkg/validate"
)

// TraceparentVersion is the version of the W3C traceparent header: used as default
const TraceparentVersion string = "00"

// TracepathKey is the key used to store the traceparent header value in http headers and grpc metadata
const TraceparentKey string = "traceparent"

// Traceparent is a struct representing the W3C traceparent header
type Traceparent struct {
	Version      string `json:"version"`                  // refers to the version of the telemetry schema
	TraceId      string `json:"transaction_id"`           // refers to the overall transaction across services
	ParentSpanId string `json:"parent_span_id,omitempty"` // refers to the caller of the current service -> span id of the caller
	SpanId       string `json:"span_id"`                  // refers to the current operation in the current service
	Flags        string `json:"flags"`
}

// GenerateSpanId generates a new span id and sets it on the Traceparent struct.
// This should be used by the receiving service to generate a new span id for the current operation.
func (t *Traceparent) GenerateSpanId() {
	t.SpanId = GenerateSpanId()
}

// BuildTraceparentString builds a W3C traceparent header value from the Traceparent fields.
// It will check if the values exist, but if they do, it assumes they are valid.
func (t *Traceparent) BuildTraceparentString(logger *slog.Logger) string {

	// check if logger is nil and set to default if so
	if logger == nil {
		logger = slog.Default()
	}

	log := logger

	// check for missing fields and generate new ones if necessary but this should not happen
	if t.Version == "" {
		t.Version = TraceparentVersion
		log.Warn("traceparent version missing, applying default", "new_version", t.Version)
	}

	if t.TraceId == "" {
		t.TraceId = GenerateTraceId()
		log.Warn("trace id missing, generating new trace id", "new_trace_id", t.TraceId)
	}

	if t.SpanId == "" {
		t.SpanId = GenerateSpanId()
		log.Warn("span id missing, generating new span id", "new_span_id", t.SpanId)
	}

	if t.Flags == "" {
		t.Flags = "00" // default to not sampled if flags are missing
		log.Warn("flags missing, applying default", "new_flags", t.Flags)
	}

	return fmt.Sprintf("%s-%s-%s-%s", t.Version, t.TraceId, t.SpanId, t.Flags)
}

// GenerateTraceId generates a Trace Id that is a 128 bits hex string
// in compliance with the W3C Trace Context specification
func GenerateTraceId() string {
	bytes := make([]byte, 16) // 16 bytes = 128 bits
	rand.Read(bytes)
	return hex.EncodeToString(bytes)
}

// GenerateSpanId generates a Span Id that is a 64 bits hex string
// in compliance with the W3C Trace Context specification
func GenerateSpanId() string {
	bytes := make([]byte, 8) // 8 bytes = 64 bits
	rand.Read(bytes)
	return hex.EncodeToString(bytes)
}

// sampledFlag is a helper function to generate a sampled flag for the traceparent header.
// It returns "01" for 1% of calls and "00" for the rest.
var sampleCounter atomic.Uint64

func sampledFlag() string {

	if sampleCounter.Add(1)%100 == 0 {

		return "01"
	}

	return "00"
}

// NewTraceparent is a factory function that returns a new Traceparent struct with generated TraceId and SpanId
func NewTraceparent() *Traceparent {

	// Note: ParentSpanId is received from the caller, so it is not generated here.
	// It should be generated by the receiving service to represent the caller of the current service.
	return &Traceparent{
		Version: TraceparentVersion,
		TraceId: GenerateTraceId(),
		SpanId:  GenerateSpanId(),
		Flags:   sampledFlag(),
	}
}

// ParseTraceparent parses a W3C traceparent http header/grpc metadata value from an http request into a Telemetry struct
func ParseTraceparent(tp string) (*Traceparent, error) {

	traceparent := strings.TrimSpace(tp)

	if traceparent == "" {
		return nil, fmt.Errorf("traceparent value is empty or missing")
	}

	// parse the traceparent header
	chunks := strings.Split(traceparent, "-")
	if len(chunks) != 4 {
		return nil, fmt.Errorf("invalid traceparent header format: expected 4 chunks, got %d", len(chunks))
	}

	version := chunks[0]
	traceId := chunks[1]
	parentId := chunks[2]
	flags := chunks[3]

	// validate the version number
	if version == "" || len(version) != 2 {
		return nil, fmt.Errorf("missing or invalid version in traceparent header")
	}

	// validate the trace id
	if err := validate.ValidateTraceId(traceId); err != nil {
		return nil, fmt.Errorf("missing or invalid trace id in traceparent header: %v", err)
	}

	// validate the parent id
	if err := validate.ValidateSpanId(parentId); err != nil {
		return nil, fmt.Errorf("missing or invalid span id in traceparent header: %v", err)
	}

	// validate the flags
	if flags == "" || len(flags) != 2 {
		return nil, fmt.Errorf("missing or invalid flags in traceparent header")
	}

	// SpanId is generated by the recieving service to represent the current operation, so
	// it is not included in the traceparent header sent by the caller
	return &Traceparent{
		Version:      version,
		TraceId:      traceId,
		ParentSpanId: parentId,
		Flags:        flags,
	}, nil
}
